In [3]:
import os 
from keras_vggface.vggface import VGGFace
import tensorflow as tf
import numpy as np
import cv2
import json
import pickle
from keras_vggface import utils


In [4]:
def process(x):
    x = tf.keras.preprocessing.image.img_to_array(x)
    x = np.expand_dims(x, axis=0)
    x = utils.preprocess_input(x, version=1)
    x = vgg_features(x)
  
    return x

In [5]:
cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml')
vgg_features = VGGFace(model='resnet50', include_top=False, input_shape=(224, 224, 3),
                               pooling='avg')  
data={}
for img in os.listdir('faces'):
    img_arr = cv2.imread(os.path.join('faces', img))[...,::-1] 
    faces = cascade.detectMultiScale(cv2.cvtColor(img_arr, cv2.COLOR_BGR2GRAY), 1.1, 7)
    for x,y,z,w in faces:
        imgs=img_arr[y:y+z,x:x+w]
        resized_arr = cv2.resize(imgs, (224, 224)) # Reshaping images to preferred size
        f_name,f_ext=os.path.splitext(img)
        resized_arr=process(resized_arr)
        data[f_name]=resized_arr


In [6]:
print(data)

{'ala': <tf.Tensor: shape=(1, 2048), dtype=float32, numpy=
array([[4.9675307 , 0.02435563, 0.        , ..., 0.        , 0.01845832,
        5.199515  ]], dtype=float32)>, 'da71': <tf.Tensor: shape=(1, 2048), dtype=float32, numpy=
array([[0.        , 0.148412  , 0.41774505, ..., 0.        , 0.06885757,
        3.266035  ]], dtype=float32)>, 'haythem': <tf.Tensor: shape=(1, 2048), dtype=float32, numpy=
array([[0.40612856, 9.22104   , 0.        , ..., 0.33715704, 0.        ,
        2.8523674 ]], dtype=float32)>, 'karam': <tf.Tensor: shape=(1, 2048), dtype=float32, numpy=
array([[0.        , 0.44186747, 0.21304277, ..., 0.        , 0.01507156,
        0.        ]], dtype=float32)>}


In [7]:
with open('faces.pkl', 'wb') as file:
      
    # A new file will be created
    pickle.dump(data, file)

NameError: name 'app_json' is not defined

In [9]:
with open('faces.pkl', 'rb') as file:
    d=pickle.load(file)